language: node_js
node_js:
- '0.10'
after_success:
- istanbul cover ./node_modules/mocha/bin/_mocha test/*tests.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: SIItonDdU4JlWQ17/MrADDykzYvGdn0MfpcwNc7SjVXafnv/ODrQPiUimHbsquX9pxcVARmDoRv5FO2KSpRRwhUthLYhWJftI7KpuKeBK9PnUmfqC452qkgmgiNW+Gzvu86Wd+cw1gDCc8Zn9o6/FR89bQkfvT0l9BVUZiC7ZxM=
  on:
    tags: true
    all_branches: true
