language: node_js
sudo: false
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - npm install -g gulp
after_success:
  - gulp ci
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: SIItonDdU4JlWQ17/MrADDykzYvGdn0MfpcwNc7SjVXafnv/ODrQPiUimHbsquX9pxcVARmDoRv5FO2KSpRRwhUthLYhWJftI7KpuKeBK9PnUmfqC452qkgmgiNW+Gzvu86Wd+cw1gDCc8Zn9o6/FR89bQkfvT0l9BVUZiC7ZxM=
  on:
    tags: true
    all_branches: true
